2023-04-01 11:28:33,133 : INFO : root : Loading config.
2023-04-01 11:28:33,525 : INFO : ConfigProcessor : Config spec file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/config_spec.mpf_cache
2023-04-01 11:28:33,525 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-01 11:28:33,525 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tpetch/Documents/trashland_3/config/config.yaml
2023-04-01 11:28:33,525 : INFO : ConfigProcessor : Loading config from file /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/mpfconfig.yaml.
2023-04-01 11:28:33,595 : INFO : ConfigProcessor : Loading config: /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/mpfconfig.yaml
2023-04-01 11:28:33,596 : INFO : ConfigProcessor : Loading config from file /Users/tpetch/Documents/trashland_3/config/config.yaml.
2023-04-01 11:28:33,732 : INFO : ConfigProcessor : Loading config: /Users/tpetch/Documents/trashland_3/config/config.yaml
2023-04-01 11:28:33,735 : INFO : ConfigProcessor : Config file cache created: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/28c67afebeedf0bcd540f5dc9898a885.mpf_cache
2023-04-01 11:28:33,770 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/03cea1619b79a61f4f0eef3c59cdaa46.mpf_cache
2023-04-01 11:28:33,771 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/d3948d842c6309f14ab557c3c72320d0.mpf_cache
2023-04-01 11:28:33,771 : INFO : ConfigProcessor : Loading config from cache: /var/folders/0y/x6b2lmrx6vq3nhkjncz48nhc0000gn/T/a37a2141962f60258a07880b3484644a.mpf_cache
2023-04-01 11:28:33,772 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.1.dev4
2023-04-01 11:28:33,772 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2023-04-01-11-28-33-mpf-Tanners-MacBook-Pro-2.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-01 11:28:33,772 : INFO : Machine : MPF path: /Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf
2023-04-01 11:28:33,772 : INFO : Machine : Machine path: /Users/tpetch/Documents/trashland_3
2023-04-01 11:28:33,772 : INFO : Machine : Platform: darwin
2023-04-01 11:28:33,772 : INFO : Machine : Python executable location: /Users/tpetch/.local/pipx/venvs/mpf/bin/python
2023-04-01 11:28:33,772 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-04-01 11:28:33,777 : INFO : Machine : Initialise MPF.
2023-04-01 11:28:33,833 : INFO : [NET] : Trying to connect to /dev/tty.usbmodem141401 at 921600bps
2023-04-01 11:28:33,840 : INFO : [NET] : Connected to /dev/tty.usbmodem141401 at 921600bps
2023-04-01 11:28:33,853 : INFO : [NET] : Connected to FP-CPU-2000 with firmware v02.06
2023-04-01 11:28:33,853 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '02.06', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,853 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-2000', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,855 : INFO : [NET] : Registered I/O Board 0: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2023-04-01 11:28:33,857 : INFO : [NET] : Registered I/O Board 1: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2023-04-01 11:28:33,858 : INFO : [NET] : Registered I/O Board 2: Model: FP-I/O-3208, Firmware: 01.09, Switches: 32, Drivers: 8
2023-04-01 11:28:33,860 : INFO : [NET] : Registered I/O Board 3: Model: FP-I/O-1616, Firmware: 01.09, Switches: 16, Drivers: 16
2023-04-01 11:28:33,861 : INFO : [NET] : Registered I/O Board 4: Model: FP-I/O-3208, Firmware: 01.09, Switches: 32, Drivers: 8
2023-04-01 11:28:33,863 : INFO : [EXP] : Trying to connect to /dev/tty.usbmodem141403 at 921600bps
2023-04-01 11:28:33,868 : INFO : [EXP] : Connected to /dev/tty.usbmodem141403 at 921600bps
2023-04-01 11:28:33,874 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,917 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-04-01 11:28:33,917 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.1.dev4', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,917 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.1.dev4, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,917 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,931 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-10.16-x86_64-i386-64bit', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,931 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,931 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '22.2.0', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,931 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,932 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2023-04-01 11:28:33,932 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-04-01 11:28:33,973 : ERROR : ConfigValidator : Your config contains a value for the setting "flippers:f_u_flipper:activation_switch:", but this is not a valid setting name.
2023-04-01 11:28:33,974 : ERROR : asyncio : Exception in callback functools.partial(<function EventManager._async_handler_done at 0x7f96e512e160>, <QueuedEvent>)
handle: <Handle functools.partial(<function EventManager._async_handler_done at 0x7f96e512e160>, <QueuedEvent>)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 121, in _async_handler_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 147, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 342, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "flippers:f_u_flipper:activation_switch:", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
2023-04-01 11:28:33,978 : INFO : Machine : Starting the main run loop.
2023-04-01 11:28:33,979 : INFO : Machine : Shutting down...
2023-04-01 11:28:33,979 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-04-01 11:28:35,088 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/events.py", line 121, in _async_handler_done
    future.result()
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device_manager.py", line 147, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "/Users/tpetch/.local/pipx/venvs/mpf/lib/python3.9/site-packages/mpf/core/config_validator.py", line 342, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "flippers:f_u_flipper:activation_switch:", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-2.html)
2023-04-01 11:28:55,915 : INFO : root : MPF run loop ended.
