2024-04-17 22:21:22,414 : INFO : root : Loading config.
2024-04-17 22:21:22,417 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-17 22:21:22,417 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tannerpetch/Documents/GitHub/lofab/config/config.yaml
2024-04-17 22:21:22,417 : INFO : ConfigProcessor : Loading config from file /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/mpfconfig.yaml.
2024-04-17 22:21:22,423 : INFO : ConfigProcessor : Loading config: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/mpfconfig.yaml
2024-04-17 22:21:22,423 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/config/config.yaml.
2024-04-17 22:21:22,427 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/config/config.yaml
2024-04-17 22:21:22,428 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/871505f0f2d2915bd502f0a1fb110f3b.mpf_cache
2024-04-17 22:21:22,451 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-17 22:21:22,451 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/edcc5f1d3215b377c9faab88c62e4ce0.mpf_cache
2024-04-17 22:21:22,452 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-17 22:21:22,452 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml
2024-04-17 22:21:22,452 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml.
2024-04-17 22:21:22,453 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/modes/base/config/base.yaml
2024-04-17 22:21:22,453 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f97c90855879603280fcc571f5c42639.mpf_cache
2024-04-17 22:21:22,453 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/modes/lane_rotate/config/lane_rotate.yaml.
2024-04-17 22:21:22,454 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/modes/lane_rotate/config/lane_rotate.yaml
2024-04-17 22:21:22,454 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/1875c266911f801b691956fe9e9284d6.mpf_cache
2024-04-17 22:21:22,454 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/3dbc438e88423aa3ff742db2713b600f.mpf_cache
2024-04-17 22:21:22,455 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/91adfe62d94491e9c757b00a8e3b96af.mpf_cache
2024-04-17 22:21:22,455 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/154d071a3850556c6f3eae37bf41c8b6.mpf_cache
2024-04-17 22:21:22,455 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/ab100dbe0e16472b56f0213f3842a00f.mpf_cache
2024-04-17 22:21:22,457 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f03ad90ccd2c053e9e5d10795d01f4ba.mpf_cache
2024-04-17 22:21:22,457 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/0f3c951d4c93079ae3fac6429c5bc2ee.mpf_cache
2024-04-17 22:21:22,457 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/8bf004783a280ac33d17b88f37848116.mpf_cache
2024-04-17 22:21:22,458 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/d5d50eaa09e055f3a827c6269a3aa165.mpf_cache
2024-04-17 22:21:22,459 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.1.dev3
2024-04-17 22:21:22,459 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-17-22-21-22-mpf-Tanners-Laptop.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-17 22:21:22,459 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf
2024-04-17 22:21:22,459 : INFO : Machine : Machine path: /Users/tannerpetch/Documents/GitHub/lofab
2024-04-17 22:21:22,459 : INFO : Machine : Platform: darwin
2024-04-17 22:21:22,459 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
2024-04-17 22:21:22,459 : INFO : Machine : Python version: 3.9.13 (64-bit)
2024-04-17 22:21:22,459 : INFO : Machine : Initializing MPF...
2024-04-17 22:21:22,488 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,502 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-04-17 22:21:22,502 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-04-17 22:21:22,502 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,502 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,502 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.3-arm64-arm-64bit', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.3.0', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.3.0: Thu Dec 21 02:29:41 PST 2023; root:xnu-10002.81.5~11/RELEASE_ARM64_T8122', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2024-04-17 22:21:22,511 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-04-17 22:21:22,521 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not a dict.')>) at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...not a dict.')>) at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py:124>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/devices/shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 274, in validate_config_item
    return self._validate_dict(item_type, validation, validation_failure_info, item)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 290, in _validate_dict
    raise self.validation_error(item, validation_failure_info, "Item is not a dict.", 12)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:base:shots:r_pop:show_tokens = "l_pop_flasher_1, l_pop_flasher_4, l_pop_flasher_7" is not valid. Item is not a dict. Error Code: CFE-ConfigValidator-12 (https://missionpinball.org/logs)
2024-04-17 22:21:22,523 : INFO : Machine : Starting the main run loop.
2024-04-17 22:21:22,523 : INFO : Machine : Shutting down...
2024-04-17 22:21:22,523 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-17 22:21:23,526 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/devices/shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 274, in validate_config_item
    return self._validate_dict(item_type, validation, validation_failure_info, item)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/config_validator.py", line 290, in _validate_dict
    raise self.validation_error(item, validation_failure_info, "Item is not a dict.", 12)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry mode:base:shots:r_pop:show_tokens = "l_pop_flasher_1, l_pop_flasher_4, l_pop_flasher_7" is not valid. Item is not a dict. Error Code: CFE-ConfigValidator-12 (https://missionpinball.org/logs)
2024-04-17 22:21:51,991 : INFO : root : MPF run loop ended.
