2024-02-01 12:32:54,053 : INFO : root : Loading config.
2024-02-01 12:32:54,057 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-02-01 12:32:54,057 : WARNING : ConfigProcessor : Config file in cache changed: C:\lofab\config\config.yaml
2024-02-01 12:32:54,057 : INFO : ConfigProcessor : Loading config from file C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\mpfconfig.yaml.
2024-02-01 12:32:54,068 : INFO : ConfigProcessor : Loading config: C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\mpfconfig.yaml
2024-02-01 12:32:54,068 : INFO : ConfigProcessor : Loading config from file C:\lofab\config\config.yaml.
2024-02-01 12:32:54,071 : INFO : ConfigProcessor : Loading config: C:\lofab\config\config.yaml
2024-02-01 12:32:54,072 : INFO : ConfigProcessor : Config file cache created: C:\Users\Tanner\AppData\Local\Temp\35bf7834a2cb30277765407e9f9dad35.mpf_cache
2024-02-01 12:32:54,142 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\a2934b2c2ffee8b0382fdb4f299381ea.mpf_cache
2024-02-01 12:32:54,143 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\dfbe1b39ae456f06de73c859384050b2.mpf_cache
2024-02-01 12:32:54,144 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\ae8c868550a49a81e63b3815e7eb5a1d.mpf_cache
2024-02-01 12:32:54,144 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\33a505bd675d22be3af5a2b10c6c9794.mpf_cache
2024-02-01 12:32:54,145 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev33
2024-02-01 12:32:54,145 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2024-02-01-12-32-54-mpf-DESKTOP-7HNFDQ5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-02-01 12:32:54,145 : INFO : Machine : MPF path: C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf
2024-02-01 12:32:54,145 : INFO : Machine : Machine path: C:\lofab
2024-02-01 12:32:54,145 : INFO : Machine : Platform: win32
2024-02-01 12:32:54,145 : INFO : Machine : Python executable location: C:\Users\Tanner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
2024-02-01 12:32:54,145 : INFO : Machine : Python version: 3.11.7 (64-bit)
2024-02-01 12:32:54,148 : INFO : Machine : Initializing MPF...
2024-02-01 12:32:54,376 : INFO : [NET] : Trying to connect to com9 at 921600bps
2024-02-01 12:32:54,454 : INFO : [NET] : Connected to com9 at 921600bps
2024-02-01 12:32:54,461 : INFO : [NET] : Connected to FP-CPU-2000 with firmware v02.13
2024-02-01 12:32:54,492 : INFO : [NET] : Registered I/O Board 0: Model: FP-I/O-0804, Firmware: 01.10, Switches: 8, Drivers: 4
2024-02-01 12:32:54,508 : INFO : [NET] : Registered I/O Board 1: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2024-02-01 12:32:54,524 : INFO : [NET] : Registered I/O Board 2: Model: FP-I/O-3208, Firmware: 01.10, Switches: 32, Drivers: 8
2024-02-01 12:32:54,525 : INFO : [EXP] : Trying to connect to com10 at 921600bps
2024-02-01 12:32:54,603 : INFO : [EXP] : Connected to com10 at 921600bps
2024-02-01 12:32:54,618 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "EXP FP-EXP-0081  0.12", board address 84
2024-02-01 12:32:54,633 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "BRK FP-EXP-0081  0.12", board address 840
2024-02-01 12:32:54,648 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "BRK FP-EXP-0081  0.12", board address 841
2024-02-01 12:32:54,664 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,678 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-02-01 12:32:54,678 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-02-01 12:32:54,678 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev33', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,678 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev33, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,678 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.7', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,687 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,687 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,687 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,687 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,688 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-02-01 12:32:54,688 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-02-01 12:32:58,854 : INFO : SwitchController : <<<<<<< 's_launch' active >>>>>>>
2024-02-01 12:32:58,854 : INFO : SwitchController : <<<<<<< 's_2' active >>>>>>>
2024-02-01 12:32:58,854 : INFO : EventManager : Event: ======'sw_playfield_active'====== Args={}
2024-02-01 12:32:58,854 : INFO : SwitchController : <<<<<<< 's_13' active >>>>>>>
2024-02-01 12:32:58,854 : INFO : EventManager : Event: ======'sw_playfield_active'====== Args={}
2024-02-01 12:32:58,854 : INFO : SwitchController : <<<<<<< 's_14' active >>>>>>>
2024-02-01 12:32:58,854 : INFO : EventManager : Event: ======'sw_playfield_active'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'playfield_active'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'unexpected_ball_on_playfield'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'playfield_active'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'unexpected_ball_on_playfield'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'playfield_active'====== Args={}
2024-02-01 12:32:58,855 : INFO : EventManager : Event: ======'unexpected_ball_on_playfield'====== Args={}
2024-02-01 12:32:58,885 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-02-01 12:32:58,886 : INFO : SwitchController : Found active switch: (10, [FAST Platform Interface]) <switch.s_launch>
2024-02-01 12:32:58,886 : INFO : SwitchController : Found active switch: (18, [FAST Platform Interface]) <switch.s_2>
2024-02-01 12:32:58,886 : INFO : SwitchController : Found active switch: (29, [FAST Platform Interface]) <switch.s_13>
2024-02-01 12:32:58,886 : INFO : SwitchController : Found active switch: (30, [FAST Platform Interface]) <switch.s_14>
2024-02-01 12:32:58,929 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-02-01 12:32:58,931 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...es:" found.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...es:" found.')>)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_display_loop" >> Invalid section "slides:" found. Context: attract_display_loop Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-02-01 12:32:58,934 : INFO : Machine : Starting the main run loop.
2024-02-01 12:32:58,937 : INFO : Machine : Shutting down...
2024-02-01 12:32:58,937 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-02-01 12:33:00,027 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 210, in _process_step_actions
    self._show_validation_error('Invalid section "{}:" found.'.format(key), 4)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\assets\show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "attract_display_loop" >> Invalid section "slides:" found. Context: attract_display_loop Error Code: CFE-show-4 (https://missionpinball.org/logs)
2024-02-01 12:33:00,030 : INFO : root : MPF run loop ended.
