2024-04-19 17:51:12,093 : INFO : root : Loading config.
2024-04-19 17:51:12,096 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-19 17:51:12,096 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/871505f0f2d2915bd502f0a1fb110f3b.mpf_cache
2024-04-19 17:51:12,120 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-19 17:51:12,120 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/edcc5f1d3215b377c9faab88c62e4ce0.mpf_cache
2024-04-19 17:51:12,120 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-19 17:51:12,120 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/1875c266911f801b691956fe9e9284d6.mpf_cache
2024-04-19 17:51:12,121 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f97c90855879603280fcc571f5c42639.mpf_cache
2024-04-19 17:51:12,121 : WARNING : ConfigProcessor : Config file in cache changed: /Users/tannerpetch/Documents/GitHub/lofab/modes/launch_shows/config/launch_shows.yaml
2024-04-19 17:51:12,121 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/modes/launch_shows/config/launch_shows.yaml.
2024-04-19 17:51:12,122 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/modes/launch_shows/config/launch_shows.yaml
2024-04-19 17:51:12,123 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/66764f8b68b26fdba6c1f2bce3638479.mpf_cache
2024-04-19 17:51:12,123 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/3dbc438e88423aa3ff742db2713b600f.mpf_cache
2024-04-19 17:51:12,124 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/91adfe62d94491e9c757b00a8e3b96af.mpf_cache
2024-04-19 17:51:12,124 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/154d071a3850556c6f3eae37bf41c8b6.mpf_cache
2024-04-19 17:51:12,124 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/ab100dbe0e16472b56f0213f3842a00f.mpf_cache
2024-04-19 17:51:12,126 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f03ad90ccd2c053e9e5d10795d01f4ba.mpf_cache
2024-04-19 17:51:12,126 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/0f3c951d4c93079ae3fac6429c5bc2ee.mpf_cache
2024-04-19 17:51:12,127 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/8bf004783a280ac33d17b88f37848116.mpf_cache
2024-04-19 17:51:12,128 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/d5d50eaa09e055f3a827c6269a3aa165.mpf_cache
2024-04-19 17:51:12,128 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/250153cb7d132f4134a2e9b694314568.mpf_cache
2024-04-19 17:51:12,129 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/bbbe87a2f82c66174798be62d4e8058c.mpf_cache
2024-04-19 17:51:12,129 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.1.dev3
2024-04-19 17:51:12,129 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-19-17-51-12-mpf-Tanners-Laptop.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-19 17:51:12,129 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf
2024-04-19 17:51:12,129 : INFO : Machine : Machine path: /Users/tannerpetch/Documents/GitHub/lofab
2024-04-19 17:51:12,129 : INFO : Machine : Platform: darwin
2024-04-19 17:51:12,129 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
2024-04-19 17:51:12,129 : INFO : Machine : Python version: 3.9.13 (64-bit)
2024-04-19 17:51:12,129 : INFO : Machine : Initializing MPF...
2024-04-19 17:51:12,160 : INFO : FAST [NET] : Trying to connect to com3 at 921600bps
2024-04-19 17:51:12,161 : ERROR : FAST [NET] : Failed to connect to any of the specified ports.
2024-04-19 17:51:12,161 : INFO : Machine : Shutting down...
2024-04-19 17:51:12,161 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-19 17:51:12,262 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/platforms/fast/fast.py", line 277, in _connect_to_hardware
    await communicator.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/platforms/fast/communicators/base.py", line 114, in connect
    raise SerialException(f"{self} could not connect to a serial port. Is it open in CoolTerm? ;)")
serial.serialutil.SerialException: [FAST NET] could not connect to a serial port. Is it open in CoolTerm? ;)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 675, in initialize_mpf
    raise init.exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 243, in initialize_core_and_hardware
    await self._initialize_platforms()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 333, in _initialize_platforms
    result.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/platforms/fast/fast.py", line 123, in initialize
    await self._connect_to_hardware()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/platforms/fast/fast.py", line 284, in _connect_to_hardware
    raise MpfRuntimeError(f"Could not open serial port {port}. Is something else connected to the port? "
mpf.exceptions.runtime_error.MpfRuntimeError: Runtime Error in FAST: Could not open serial port net. Is something else connected to the port? Did the port number or your computer change? Do you have permissions to access the port? Error Code: RE-FAST-1 (https://missionpinball.org/logs)
2024-04-19 17:51:14,605 : INFO : root : MPF run loop ended.
