2024-02-01 16:22:18,019 : INFO : root : Loading config.
2024-02-01 16:22:18,023 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-02-01 16:22:18,024 : WARNING : ConfigProcessor : Config file in cache changed: c:\lofab\config\config.yaml
2024-02-01 16:22:18,024 : INFO : ConfigProcessor : Loading config from file C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\mpfconfig.yaml.
2024-02-01 16:22:18,035 : INFO : ConfigProcessor : Loading config: C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\mpfconfig.yaml
2024-02-01 16:22:18,036 : INFO : ConfigProcessor : Loading config from file c:\lofab\config\config.yaml.
2024-02-01 16:22:18,039 : INFO : ConfigProcessor : Loading config: c:\lofab\config\config.yaml
2024-02-01 16:22:18,040 : INFO : ConfigProcessor : Config file cache created: C:\Users\Tanner\AppData\Local\Temp\ae594c12e5b61ed7124eed45950049a7.mpf_cache
2024-02-01 16:22:18,110 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\165ae565642a148ddd3c4976ade4dd88.mpf_cache
2024-02-01 16:22:18,111 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\dfbe1b39ae456f06de73c859384050b2.mpf_cache
2024-02-01 16:22:18,112 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev33
2024-02-01 16:22:18,112 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2024-02-01-16-22-18-mpf-DESKTOP-7HNFDQ5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-02-01 16:22:18,112 : INFO : Machine : MPF path: C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf
2024-02-01 16:22:18,112 : INFO : Machine : Machine path: c:\lofab
2024-02-01 16:22:18,113 : INFO : Machine : Platform: win32
2024-02-01 16:22:18,113 : INFO : Machine : Python executable location: C:\Users\Tanner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
2024-02-01 16:22:18,113 : INFO : Machine : Python version: 3.11.7 (64-bit)
2024-02-01 16:22:18,115 : INFO : Machine : Initializing MPF...
2024-02-01 16:22:18,354 : INFO : [NET] : Trying to connect to com9 at 921600bps
2024-02-01 16:22:18,431 : INFO : [NET] : Connected to com9 at 921600bps
2024-02-01 16:22:18,435 : INFO : [NET] : Connected to FP-CPU-2000 with firmware v02.13
2024-02-01 16:22:18,467 : INFO : [NET] : Registered I/O Board 0: Model: FP-I/O-0804, Firmware: 01.10, Switches: 8, Drivers: 4
2024-02-01 16:22:18,483 : INFO : [NET] : Registered I/O Board 1: Model: FP-I/O-0804, Firmware: 01.09, Switches: 8, Drivers: 4
2024-02-01 16:22:18,499 : INFO : [NET] : Registered I/O Board 2: Model: FP-I/O-3208, Firmware: 01.10, Switches: 32, Drivers: 8
2024-02-01 16:22:18,500 : INFO : [EXP] : Trying to connect to com10 at 921600bps
2024-02-01 16:22:18,578 : INFO : [EXP] : Connected to com10 at 921600bps
2024-02-01 16:22:18,592 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "EXP FP-EXP-0081  0.12", board address 84
2024-02-01 16:22:18,608 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "BRK FP-EXP-0081  0.12", board address 840
2024-02-01 16:22:18,623 : INFO : [EXP] : Verifying hardware for EXP "pf" (FP-EXP-0081, @84) with ID string "BRK FP-EXP-0081  0.12", board address 841
2024-02-01 16:22:18,639 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,654 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-02-01 16:22:18,654 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-02-01 16:22:18,654 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev33', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,654 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev33, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,654 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.7', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-02-01 16:22:18,663 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-02-01 16:22:20,803 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe... Interface]')>) at C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\utility_functions.py:784
handle: <Handle Util.raise_exceptions(<Task finishe... Interface]')>) at C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\utility_functions.py:784>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\utility_functions.py", line 792, in raise_exceptions
    future.result()
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 338, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 347, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 314, in _process_switch_closed
    self.machine.switch_controller.process_switch_by_num(state=1,
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\switch_controller.py", line 251, in process_switch_by_num
    raise AssertionError("Got early switch change for switch {} to state {}. platform: {}".format(
AssertionError: Got early switch change for switch 11 to state 1. platform: [FAST Platform Interface]
2024-02-01 16:22:20,806 : INFO : Machine : Starting the main run loop.
2024-02-01 16:22:20,809 : INFO : Machine : Shutting down...
2024-02-01 16:22:20,809 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-02-01 16:22:21,901 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\utility_functions.py", line 792, in raise_exceptions
    future.result()
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 338, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\base.py", line 347, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 314, in _process_switch_closed
    self.machine.switch_controller.process_switch_by_num(state=1,
  File "C:\Users\Tanner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mpf\core\switch_controller.py", line 251, in process_switch_by_num
    raise AssertionError("Got early switch change for switch {} to state {}. platform: {}".format(
AssertionError: Got early switch change for switch 11 to state 1. platform: [FAST Platform Interface]
2024-02-01 16:22:21,904 : INFO : root : MPF run loop ended.
